// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqAPiJumkrbUNluLDVWCYELAlNvEhRc2I',
    appId: '1:853136954941:web:a1c24c7b4360971ecbbc54',
    messagingSenderId: '853136954941',
    projectId: 'fcm-hris-5763a',
    authDomain: 'fcm-hris-5763a.firebaseapp.com',
    storageBucket: 'fcm-hris-5763a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGMYV6Cxy7KD6miagzlKuy2iRtjlK8sPU',
    appId: '1:853136954941:android:24b65a363ea5d14bcbbc54',
    messagingSenderId: '853136954941',
    projectId: 'fcm-hris-5763a',
    storageBucket: 'fcm-hris-5763a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKc7W_xAdilm9DehyCwIxYRd5jFUXNKY8',
    appId: '1:853136954941:ios:91199f534939bccccbbc54',
    messagingSenderId: '853136954941',
    projectId: 'fcm-hris-5763a',
    storageBucket: 'fcm-hris-5763a.firebasestorage.app',
    iosBundleId: 'com.example.hr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKc7W_xAdilm9DehyCwIxYRd5jFUXNKY8',
    appId: '1:853136954941:ios:91199f534939bccccbbc54',
    messagingSenderId: '853136954941',
    projectId: 'fcm-hris-5763a',
    storageBucket: 'fcm-hris-5763a.firebasestorage.app',
    iosBundleId: 'com.example.hr',
  );
}
